### PR TITLE
Modify the license to upload to crates.io.

### PR DESCRIPTION
**Pull request by Shylock-Hg**
See https://github.com/rust-lang/cargo/issues/2174#issuecomment-160314539 for crates.io now try check the license by spdx, and spdx not introduce the common clause in https://github.com/spdx/license-list-XML/issues/902

### CODE REVIEW

**Comment by darionyaphet** [comment]
Is it need to be consistent with the main repo ?

**Comment by Shylock-Hg** [comment]
> Is it need to be consistent with the main repo ?

In my think, the client don't need the cc license. CC is used to prevent SasS provider, the client has no this issue.

**Comment by visortelle** [comment]
Any news on this PR?

**Comment by Shylock-Hg** [comment]
> Any news on this PR?

Our reviewer don't agree to.

**Comment by visortelle** [comment]
But you need to make some decision on it anyway. 🙂

I'll provide some options I found:

**SPDX LienseRef with a custom license**

Consider [SPDX LicenseRef](https://spdx.github.io/spdx-spec/6-other-licensing-information-detected/).

> This section is used for any detected, declared, or concluded licenses that are NOT on the SPDX License List.

It will look something like `LicenseRef-Nebula-Graph-1.0`.

Additionally use [`license-file`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields) Cargo.toml field.

**Server Side Public License (SSPL) v1**

MongoDB and Elasticsearch use this license.

It's a valid SPDX license: https://spdx.org/licenses/SSPL-1.0.html

https://github.com/elastic/elasticsearch/blob/master/LICENSE.txt

https://github.com/mongodb/mongo/blob/master/LICENSE-Community.txt

**Business Source License 1.1 (BSL)**

https://github.com/cockroachdb/cockroach/blob/master/LICENSE

It's a valid SPDX license: https://spdx.org/licenses/BUSL-1.1.html

---

As both mentioned licenses are valid SPDX licenses, you should be able to combine any of them with Apache-2.0 as it has done here: https://github.com/kubo/rust-oracle/blob/7832f993c207904dcca0186f3fb8cac75404c508/Cargo.toml#L7

---

I also don't see any sense in the proprietary license for the database client code. @laura-ding did you ever saw such examples? Maybe I'm missing something.

Thank you.

**Comment by Shylock-Hg** [comment]
> But you need to make some decision on it anyway. 🙂
> 
> I'll provide some options I found:
> 
> **SPDX LienseRef with a custom license**
> 
> Consider [SPDX LicenseRef](https://spdx.github.io/spdx-spec/6-other-licensing-information-detected/).
> 
> > This section is used for any detected, declared, or concluded licenses that are NOT on the SPDX License List.
> 
> It will look something like `LicenseRef-Nebula-Graph-1.0`.
> 
> Additionally use [`license-file`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields) Cargo.toml field.
> 
> **Server Side Public License (SSPL) v1**
> 
> MongoDB and Elasticsearch use this license.
> 
> It's a valid SPDX license: https://spdx.org/licenses/SSPL-1.0.html
> 
> https://github.com/elastic/elasticsearch/blob/master/LICENSE.txt
> 
> https://github.com/mongodb/mongo/blob/master/LICENSE-Community.txt
> 
> **Business Source License 1.1 (BSL)**
> 
> https://github.com/cockroachdb/cockroach/blob/master/LICENSE
> 
> It's a valid SPDX license: https://spdx.org/licenses/BUSL-1.1.html
> 
> As both mentioned licenses are valid SPDX licenses, you should be able to combine any of them with Apache-2.0 as it has done here: https://github.com/kubo/rust-oracle/blob/7832f993c207904dcca0186f3fb8cac75404c508/Cargo.toml#L7
> 
> I also don't see any sense in the proprietary license for the database client code. @laura-ding did you ever saw such examples? Maybe I'm missing something.
> 
> Thank you.

Yes, thanks for suggestion. My member prefer to let user include the source directly instead of add as library. And I will try to push this PR before this client release.

**Comment by wey-gu** [comment]
@Shylock-Hg as we changed to apache 2.0(removing cc), thus it's good to go with SPDX, right? :D

**Comment by Shylock-Hg** [comment]
> @Shylock-Hg as we changed to apache 2.0(removing cc), thus it's good to go with SPDX, right? :D

Yes

**Comment by Sophie-Xie** [comment]
Too long, close it.

**Pull request closed without merging**
